version: "3.4"

# Production environment override
services:
  php:
    environment:
      - APP_SECRET=${APP_SECRET}
      - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN}

  database:
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
